server:
  port: 8888

jasypt:
  encryptor:
    password: ${ENCRYPT_KEY}

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(8dXhFlAqq7PxgtS1rBsBFlx6CQl+npOWGKTlySA0HNe5N0FOPfsf44IwzbYNRB7kTHfwykXIKE/yVDilMAhfEDX9Jnui9siSl+JEVh2MZceEQlxgK+nc4AhAhBmFNZb6ZCy8OOEvTSX0qaRjsm5iCA==)
    username: ENC(8Yq7h6TkqZz6Z6e66c8mWAv1opA1nKaZ)
    password: ENC(qs5Od7qZQrBGSPLFYfw0j8+frrUUl3Z3)

  jpa:
    show-sql: true
    database: mysql
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create