server:
  port: 8888

jasypt:
  encryptor:
    password: ${ENCRYPT_KEY}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(8dXhFlAqq7PxgtS1rBsBFlx6CQl+npOWGKTlySA0HNe5N0FOPfsf44IwzbYNRB7kTHfwykXIKE/yVDilMAhfEDX9Jnui9siSl+JEVh2MZceEQlxgK+nc4AhAhBmFNZb6ZCy8OOEvTSX0qaRjsm5iCA==)
    username: ENC(8Yq7h6TkqZz6Z6e66c8mWAv1opA1nKaZ)
    password: ENC(qs5Od7qZQrBGSPLFYfw0j8+frrUUl3Z3)

  data:
    redis:
      repositories:
        enabled: false
      host: ENC(Lgvt2ysV2Bxzqx8RDiwQ5t8OhC8jlPSZ)
      port: 6379
      password: ENC(QRbRfXgO4UUWa0ztmn3cj1fR/lmlzQ+9XWam8bhAt4dcWvN+4XQuSyNLvYaNOznqfmohdnqiotNfCUEIcYNwe7maMf2ApcW8JOqCrOQizEg=)

  cache:
    type: redis

  jpa:
    show-sql: true
    database: mysql
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(EpxmRbpLQRpxBoTgrj+Uvy32d7dNLpQlmaB1KAI3ax6dfDpOIXex2A==)
    password: ENC(tyliDNLbeLkoR7Lb4pHD49aH0msapl6r/4BuvHsgtfo=)
    properties:
      mail.smtp.auth: true
      mail.starttls.enable: true
      mail.smtp.debug: true
      mail.smtp.connectiontimeout: 1000